---
- name: "Apache - Installation"
  yum:
    name:
      - httpd
      - php
    state: present
        
- name: "Apache - Copying Configuration File"
  template:
    src: httpd.conf.tmpl
    dest: /etc/httpd/conf/httpd.conf    

    
- name: "Apache - Copying Virtualhost template"
  template:
    src: virtualhost.conf.tmpl
    dest: "/etc/httpd/conf.d/{{ domain }}.conf"

- name: "Apache - Creading DocumentRoot"
  file:
    path: "/var/www/html/{{ domain }}"
    state: directory
        
- name: "Apache - Creating test.html"
  copy:
    src: index.html
    dest: "/var/www/html/{{ domain }}/index.html"
        
- name: "Apache - Creating test.php"
  copy:
    src: index.php
    dest: "/var/www/html/{{ domain }}/index.php" 
        
- name: "Apache - Restating"
  service:
    name: httpd
    state: restarted
    enabled: true
        
- name: "Mariadb-Server - Installation"
  yum:
    name:
      - mariadb-server
      - MySQL-python
      - php-mysql
    state: present

- name: "Mariadb-Server - Restart/Enable"
  service:
    name: mariadb
    state: restarted
    enabled: true
        
- name: "Mariadb-Server - Resetting Root Password"
  ignore_errors: true
  mysql_user:
    login_user: "root"
    login_password: ""
    name: "root"
    password: "{{ mysql_root }}"
    host_all: true
        
- name: "Mariadb-Server - Removing Anonymous Users"
  mysql_user:
    login_user: "root"
    login_password: "{{ mysql_root }}"
    name: ""
    state: absent
    host_all: true
        
- name: "Mariadb-Server - creating Database"
  mysql_db:
    login_user: "root"
    login_password: "{{ mysql_root }}"
    name: "{{ mysql_database}}"
    state: present
        
- name: "Mariadb-Server - Creating User"
  mysql_user:
    login_user: "root"
    login_password: "{{ mysql_root }}"
    name: "{{ mysql_user }}"
    password: "{{ mysql_password}}"
    state: present
    priv: '{{ mysql_database }}.*:ALL'
        

- name: "wordpress - Restart"
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  with_items:
    - httpd
    - mariadb
